services:

  db:
    image: postgres:14.0-alpine
    container_name: db_outlay
    volumes:
      - db_outlay_vol:/var/lib/postgresql/data
    env_file:
      - .env.dev

  web:
    build: .
    container_name: outlay
    command: >
      sh -c "python manage.py makemigrations --noinput && 
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db


  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  worker:
    restart: always
    build: .
    volumes:
      - ./:/code
    depends_on:
      - redis
      - web
    command: 'celery -A config worker -l info'

volumes:
  db_outlay_vol: