# Generated by Django 4.1.2 on 2022-11-05 23:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.base.genrate_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=src.base.genrate_path.generate_user_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('type', models.CharField(choices=[('tz', 'ТЗ'), ('spgz', 'СПГЗ')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('is_address', models.BooleanField(default=True)),
                ('price_list', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SN',
            fields=[
                ('cipher', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('spgz_name', models.CharField(max_length=150)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kpzg', models.CharField(max_length=150)),
                ('unit2', models.CharField(max_length=150)),
                ('quantity2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SNFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=src.base.genrate_path.generate_user_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
            ],
        ),
        migrations.CreateModel(
            name='SPGZ',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kpzg', models.TextField()),
                ('spgz_name', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=10)),
                ('okpd', models.CharField(max_length=50)),
                ('okpd2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SPGZFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=src.base.genrate_path.generate_user_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('kpzg', models.CharField(max_length=150)),
                ('name_spgz', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=src.base.genrate_path.generate_user_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
            ],
        ),
        migrations.CreateModel(
            name='TSN',
            fields=[
                ('cipher', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('spgz_name', models.CharField(max_length=150)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kpzg', models.CharField(max_length=150)),
                ('unit2', models.CharField(max_length=150)),
                ('quantity2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TSNFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=src.base.genrate_path.generate_user_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
            ],
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpgz', models.IntegerField()),
                ('work_code', models.IntegerField()),
                ('name_of_works', models.TextField(max_length=500)),
                ('unit_of_measurement', models.CharField(max_length=50)),
                ('spgz', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('unit_price_tru', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_tru', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.estimate')),
            ],
        ),
    ]
