# Generated by Django 4.1.2 on 2022-11-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_spgz_spgz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spgz',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
